application: hlilje-app
version: 1
runtime: go
api_version: go1

handlers:
- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /photo
  static_dir: photo

- url: /media
  static_dir: media

- url: /templates
  static_dir: templates

- url: /component
  static_dir: component

- url: /components
  static_dir: components

- url: /.*
  script: _go_app
